sudo: required
language: node_js
node_js:
  - '8'
cache: npm
install:
  - npm install npm -g
  - npm config set audit false
  - npm install
script:
  - npm run travis-ci
env:
  - CXX=g++-4.8 SKIP_ACCESSIBILITY_TESTS=true
  - CXX=g++-4.8 SKIP_LINT_TESTS=true SKIP_KARMA_TESTS=true SKIP_SNAPSHOT_TESTS=true SKIP_DOCGEN=true
addons:
  chrome: stable
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
